-- =============================================================
-- 03_crear_dimensiones.sql
-- Creacion de todas las tablas del modelo dimensional en CORE
-- Ejecutado: 2026-03-23 | Conexion: TXA18114 | Role: ACCOUNTADMIN
-- Proyecto: Leads Snowflake WT25 - EGOS BI
-- =============================================================

USE DATABASE DB_LEADS_SNOWFLAKE_WT25;
USE SCHEMA CORE;

-- =============================================================
-- SECCION 1: Tablas de referencia
-- =============================================================

-- Catalogo de industrias
CREATE OR REPLACE TABLE DIM_INDUSTRIAS (
    INDUSTRIA_ID        INT AUTOINCREMENT START 1 INCREMENT 1,
    INDUSTRIA_NOMBRE    VARCHAR(200) NOT NULL,
    ACTIVO              BOOLEAN DEFAULT TRUE,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_INDUSTRIAS PRIMARY KEY (INDUSTRIA_ID)
);

-- Ejecutivos de ventas
CREATE OR REPLACE TABLE DIM_EJECUTIVOS (
    EJECUTIVO_ID    INT AUTOINCREMENT START 1 INCREMENT 1,
    NOMBRE          VARCHAR(200) NOT NULL,
    APELLIDO        VARCHAR(200),
    EMAIL           VARCHAR(300),
    TELEFONO        VARCHAR(50),
    ACTIVO          BOOLEAN DEFAULT TRUE,
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_EJECUTIVOS PRIMARY KEY (EJECUTIVO_ID)
);

-- =============================================================
-- SECCION 2: Territorios (por industria y/o geografia)
-- =============================================================

CREATE OR REPLACE TABLE DIM_TERRITORIOS (
    TERRITORIO_ID   INT AUTOINCREMENT START 1 INCREMENT 1,
    NOMBRE          VARCHAR(200) NOT NULL,
    DESCRIPCION     VARCHAR(500),
    EJECUTIVO_ID    INT,
    REGION          VARCHAR(100),
    PAIS            VARCHAR(100) DEFAULT 'Mexico',
    ACTIVO          BOOLEAN DEFAULT TRUE,
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_TERRITORIOS PRIMARY KEY (TERRITORIO_ID),
    CONSTRAINT FK_TERRITORIOS_EJECUTIVO FOREIGN KEY (EJECUTIVO_ID)
        REFERENCES DIM_EJECUTIVOS(EJECUTIVO_ID)
);

-- Relacion N:N entre territorios e industrias
CREATE OR REPLACE TABLE REL_TERRITORIO_INDUSTRIA (
    TERRITORIO_ID   INT NOT NULL,
    INDUSTRIA_ID    INT NOT NULL,
    CREATED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_REL_TERR_IND PRIMARY KEY (TERRITORIO_ID, INDUSTRIA_ID),
    CONSTRAINT FK_REL_TERRITORIO FOREIGN KEY (TERRITORIO_ID) REFERENCES DIM_TERRITORIOS(TERRITORIO_ID),
    CONSTRAINT FK_REL_INDUSTRIA FOREIGN KEY (INDUSTRIA_ID) REFERENCES DIM_INDUSTRIAS(INDUSTRIA_ID)
);

-- =============================================================
-- SECCION 3: Cuentas (Empresas) - tabla principal
-- =============================================================

CREATE OR REPLACE TABLE DIM_CUENTAS (
    CUENTA_ID               INT AUTOINCREMENT START 1 INCREMENT 1,
    ACCT_NAME               VARCHAR(500) NOT NULL,
    INDUSTRIA_ID            INT,
    TERRITORIO_ID           INT,
    FUENTE_CLASIFICACION    VARCHAR(50),
    -- Datos demograficos (enriquecimiento)
    SITIO_WEB               VARCHAR(500),
    UBICACION               VARCHAR(300),
    PAIS                    VARCHAR(100),
    ESTADO                  VARCHAR(100),
    CIUDAD                  VARCHAR(100),
    LINKEDIN_EMPRESA        VARCHAR(500),
    REVENUE_ESTIMADO_USD    NUMERIC(15,2),
    NUM_EMPLEADOS_ESTIMADO  INT,
    TAMANO_EMPRESA          VARCHAR(20),
    FUENTE_TAMANO           VARCHAR(50),
    INDUSTRIA_DETALLE       VARCHAR(300),
    -- Seguimiento comercial
    ESTATUS                 VARCHAR(50) DEFAULT 'PENDIENTE',
    EJECUTIVO_ID            INT,
    FECHA_PRIMER_CONTACTO   TIMESTAMP_NTZ,
    FECHA_ULTIMO_CONTACTO   TIMESTAMP_NTZ,
    NOTAS                   VARCHAR(2000),
    APOLLO_SEARCHED         BOOLEAN DEFAULT FALSE,
    -- Metadata
    FUENTE_LEAD             VARCHAR(100) DEFAULT 'SNOWFLAKE_WORLD_TOUR_2025',
    CREATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CUENTAS PRIMARY KEY (CUENTA_ID),
    CONSTRAINT FK_CUENTAS_INDUSTRIA FOREIGN KEY (INDUSTRIA_ID) REFERENCES DIM_INDUSTRIAS(INDUSTRIA_ID),
    CONSTRAINT FK_CUENTAS_TERRITORIO FOREIGN KEY (TERRITORIO_ID) REFERENCES DIM_TERRITORIOS(TERRITORIO_ID),
    CONSTRAINT FK_CUENTAS_EJECUTIVO FOREIGN KEY (EJECUTIVO_ID) REFERENCES DIM_EJECUTIVOS(EJECUTIVO_ID)
);

-- =============================================================
-- SECCION 4: Contactos (N:1 con Cuentas)
-- =============================================================

CREATE OR REPLACE TABLE DIM_CONTACTOS (
    CONTACTO_ID         INT AUTOINCREMENT START 1 INCREMENT 1,
    CUENTA_ID           INT NOT NULL,
    PRIMER_NOMBRE       VARCHAR(200),
    APELLIDO            VARCHAR(300),
    NOMBRE_COMPLETO     VARCHAR(500),
    CARGO               VARCHAR(300),
    NIVEL_CARGO         VARCHAR(50),
    DEPARTAMENTO        VARCHAR(100),
    EMAIL               VARCHAR(300),
    WHATSAPP            VARCHAR(50),
    LINKEDIN_PERFIL     VARCHAR(500),
    -- Seguimiento comercial del contacto
    CONTACTADO          BOOLEAN DEFAULT FALSE,
    FECHA_CONTACTO      TIMESTAMP_NTZ,
    METODO_CONTACTO     VARCHAR(50),
    RESPUESTA           VARCHAR(50),
    NOTAS_CONTACTO      VARCHAR(2000),
    -- Metadata
    FUENTE              VARCHAR(100) DEFAULT 'EVENTO_WT25',
    PRIORIDAD           INT DEFAULT 1,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CONTACTOS PRIMARY KEY (CONTACTO_ID),
    CONSTRAINT FK_CONTACTO_CUENTA FOREIGN KEY (CUENTA_ID) REFERENCES DIM_CUENTAS(CUENTA_ID)
);

-- =============================================================
-- SECCION 5: Casos de uso por industria (Cortex AI)
-- =============================================================

CREATE OR REPLACE TABLE DIM_CASOS_USO (
    CASO_ID                 INT AUTOINCREMENT START 1 INCREMENT 1,
    INDUSTRIA_ID            INT NOT NULL,
    TENDENCIAS_INDUSTRIA    VARCHAR(5000),
    RETOS_PRINCIPALES       VARCHAR(5000),
    CASOS_USO_SNOWFLAKE     VARCHAR(5000),
    PROPUESTA_VALOR         VARCHAR(5000),
    CREATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CASOS_USO PRIMARY KEY (CASO_ID),
    CONSTRAINT FK_CASOS_INDUSTRIA FOREIGN KEY (INDUSTRIA_ID) REFERENCES DIM_INDUSTRIAS(INDUSTRIA_ID)
);

-- =============================================================
-- SECCION 6: Historial de interacciones comerciales
-- =============================================================

CREATE OR REPLACE TABLE FACT_INTERACCIONES (
    INTERACCION_ID      INT AUTOINCREMENT START 1 INCREMENT 1,
    CUENTA_ID           INT NOT NULL,
    CONTACTO_ID         INT,
    EJECUTIVO_ID        INT,
    TIPO                VARCHAR(50) NOT NULL,
    FECHA               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DESCRIPCION         VARCHAR(2000),
    RESULTADO           VARCHAR(50),
    SIGUIENTE_ACCION    VARCHAR(500),
    FECHA_SIGUIENTE     TIMESTAMP_NTZ,
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_INTERACCIONES PRIMARY KEY (INTERACCION_ID),
    CONSTRAINT FK_INTER_CUENTA FOREIGN KEY (CUENTA_ID) REFERENCES DIM_CUENTAS(CUENTA_ID),
    CONSTRAINT FK_INTER_CONTACTO FOREIGN KEY (CONTACTO_ID) REFERENCES DIM_CONTACTOS(CONTACTO_ID),
    CONSTRAINT FK_INTER_EJECUTIVO FOREIGN KEY (EJECUTIVO_ID) REFERENCES DIM_EJECUTIVOS(EJECUTIVO_ID)
);

-- Verificacion
SELECT 'Modelo dimensional creado' AS STATUS;
